import {
  Attachment,
  AuditLog,
  Machine,
  UserProfile,
  Department,
  MaintenanceRecord,
  RepairRecord,
  MachinePart,
  PartReplacement,
  MachineStatus,
  MachineType,
  MaintenancePlan,
  MaintenanceType,
  MaintenanceStatus,
  RecurrenceUnit,
  DashboardSummary,
} from './types';
import { isDueSoon, isOverdue } from './maintenance-window';

export const mockUsers: Record<string, UserProfile> = {
  'officer@sail.in': {
    id: 'u1',
    name: 'Rajesh Verma',
    email: 'officer@sail.in',
    phone: '+91 70000 00001',
    role: 'officer',
    department: 'Sinter Plant 3',
    // Officers see only their associated departments, never the whole plant.
    departmentScope: [
      'Sinter Plant 3',
      'Coal Handling',
      'Coke Ovens',
      'Blast Furnaces',
      'Plate Mill',
      'Power Plants',
    ],
    position: 'Maintenance Officer',
    status: 'active',
    lastLogin: new Date().toISOString(),
    avatarInitials: 'RV',
  },
  'supervisor@sail.in': {
    id: 'u2',
    name: 'Suresh Patel',
    email: 'supervisor@sail.in',
    phone: '+91 70000 00002',
    role: 'supervisor',
    department: 'Coal Handling',
    departmentScope: ['Coal Handling'],
    position: 'Shift Supervisor',
    status: 'active',
    lastLogin: new Date().toISOString(),
    avatarInitials: 'SP',
  },
};

export const DEMO_PASSWORD = 'Demo@1234';

/**
 * Maintenance technicians. Not application users — technicians do not sign in, they
 * are simply who a maintenance record or plan credits the work to.
 */
export interface Technician {
  id: string;
  name: string;
}

export const mockTechnicians: Technician[] = [
  { id: 't1', name: 'R. Kumar' },
  { id: 't2', name: 'S. Sharma' },
  { id: 't3', name: 'A. Patel' },
  { id: 't4', name: 'M. Singh' },
  { id: 't5', name: 'T. Das' },
];

/**
 * Departments modelled on the production facilities published on SAIL's Bhilai Steel
 * Plant facilities page, plus the codes the user supplied (SP3, CHM, Coke Oven).
 *
 * These are **provisional**. The public page lists production facilities, not BSP's
 * internal maintenance department master, so official codes, names, display order, and
 * active state still need confirmation. `head` and `machineCount` are placeholders.
 */
export const mockDepartments: Department[] = [
  // Coke ovens and coal chemicals
  { id: 'd1', name: 'Coke Ovens', code: 'COB', head: 'M. Singh', machineCount: 0 },
  { id: 'd2', name: 'Coal Chemicals', code: 'CC', head: 'A. Kumar', machineCount: 0 },
  { id: 'd3', name: 'Coal Handling', code: 'CHM', head: 'P. Das', machineCount: 0 },
  // Iron making
  { id: 'd4', name: 'Sinter Plant 2', code: 'SP2', head: 'S. Sharma', machineCount: 0 },
  { id: 'd5', name: 'Sinter Plant 3', code: 'SP3', head: 'K. Nair', machineCount: 0 },
  { id: 'd6', name: 'Blast Furnaces', code: 'BF', head: 'R. Gupta', machineCount: 0 },
  // Steel making
  { id: 'd7', name: 'Steel Melting Shop 2', code: 'SMS2', head: 'V. Patel', machineCount: 0 },
  { id: 'd8', name: 'Steel Melting Shop 3', code: 'SMS3', head: 'T. Rao', machineCount: 0 },
  { id: 'd9', name: 'Continuous Casting Shop', code: 'CCS', head: 'B. Nair', machineCount: 0 },
  // Rolling mills
  { id: 'd10', name: 'Rail & Structural Mill', code: 'RSM', head: 'D. Joshi', machineCount: 0 },
  { id: 'd11', name: 'Universal Rail Mill', code: 'URM', head: 'H. Iyer', machineCount: 0 },
  { id: 'd12', name: 'Merchant Mill', code: 'MM', head: 'N. Bose', machineCount: 0 },
  { id: 'd13', name: 'Wire Rod Mill', code: 'WRM', head: 'G. Menon', machineCount: 0 },
  { id: 'd14', name: 'Bar & Rod Mill', code: 'BRM', head: 'L. Pillai', machineCount: 0 },
  { id: 'd15', name: 'Plate Mill', code: 'PM', head: 'S. Reddy', machineCount: 0 },
  // Auxiliary units
  { id: 'd16', name: 'Power Plants', code: 'PP', head: 'J. Mishra', machineCount: 0 },
  { id: 'd17', name: 'Oxygen Plants', code: 'OP', head: 'C. Verma', machineCount: 0 },
  {
    id: 'd18',
    name: 'Refractory Materials Plant',
    code: 'RMP',
    head: 'U. Shukla',
    machineCount: 0,
  },
  {
    id: 'd19',
    name: 'Foundry & Engineering Shops',
    code: 'FES',
    head: 'Y. Kulkarni',
    machineCount: 0,
  },
  { id: 'd20', name: 'Slag Granulation Plant', code: 'SGP', head: 'O. Chauhan', machineCount: 0 },
  {
    id: 'd21',
    name: 'Traffic & Material Handling',
    code: 'TMH',
    head: 'W. Saxena',
    machineCount: 0,
  },
];

/** Department id -> name, so machine fixtures cannot drift from the department list. */
const departmentNameById = new Map(mockDepartments.map((d) => [d.id, d.name]));

function departmentName(departmentId: string): string {
  return departmentNameById.get(departmentId) ?? 'Unassigned';
}

/** Derives `machineCount` from the machine fixtures so the two can never disagree. */
function syncDepartmentMachineCounts(): void {
  for (const department of mockDepartments) {
    department.machineCount = mockMachines.filter(
      (machine) => machine.departmentId === department.id && !machine.isArchived,
    ).length;
  }
}

export const mockMachines: Machine[] = [
  {
    id: 'm1',
    code: 'HP-04',
    name: 'Hydraulic Press',
    department: departmentName('d15'),
    departmentId: 'd15',
    type: 'press',
    manufacturer: 'Bosch Rexroth',
    model: 'H-5000',
    location: 'Bay 3',
    status: 'active',
    installationDate: '2019-03-15',
    lastMaintenanceDate: '2023-09-10',
    nextMaintenanceDate: new Date(Date.now() + 15 * 86400000).toISOString(),
    description:
      'Heavy duty hydraulic press used for forming thick steel plates. Requires regular fluid level checks.',
    isArchived: false,
    createdAt: '2019-03-15',
    updatedAt: '2023-09-10',
  },
  {
    id: 'm2',
    code: 'RM-12',
    name: 'Rolling Mill Motor',
    department: departmentName('d10'),
    departmentId: 'd10',
    type: 'motor',
    manufacturer: 'Siemens',
    model: 'RM-XL',
    location: 'Bay 7',
    status: 'under_maintenance',
    installationDate: '2017-08-20',
    lastMaintenanceDate: '2023-05-15',
    nextMaintenanceDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    description: 'Primary drive motor for roughing stand.',
    isArchived: false,
    createdAt: '2017-08-20',
    updatedAt: '2023-10-01',
  },
  {
    id: 'm3',
    code: 'CWP-08',
    name: 'Cooling Water Pump',
    department: departmentName('d16'),
    departmentId: 'd16',
    type: 'pump',
    manufacturer: 'Grundfos',
    model: 'CR-150',
    location: 'Pump House',
    status: 'active',
    installationDate: '2020-01-10',
    lastMaintenanceDate: '2023-08-20',
    nextMaintenanceDate: new Date(Date.now() + 45 * 86400000).toISOString(),
    description: 'Circulates cooling water to the primary blast furnace.',
    isArchived: false,
    createdAt: '2020-01-10',
    updatedAt: '2023-08-20',
  },
  {
    id: 'm4',
    code: 'OC-03',
    name: 'Overhead Crane',
    department: departmentName('d7'),
    departmentId: 'd7',
    type: 'crane',
    manufacturer: 'Demag',
    model: 'V-Type',
    location: 'Bay 1-3 Overhead',
    status: 'active',
    installationDate: '2016-05-12',
    lastMaintenanceDate: '2023-07-11',
    nextMaintenanceDate: new Date(Date.now() + 60 * 86400000).toISOString(),
    description: '100T capacity overhead crane spanning bays 1 through 3.',
    isArchived: false,
    createdAt: '2016-05-12',
    updatedAt: '2023-07-11',
  },
  {
    id: 'm5',
    code: 'AC-06',
    name: 'Air Compressor',
    department: departmentName('d17'),
    departmentId: 'd17',
    type: 'compressor',
    manufacturer: 'Atlas Copco',
    model: 'GA 90',
    location: 'Compressor Room',
    status: 'active',
    installationDate: '2021-02-28',
    lastMaintenanceDate: '2023-09-01',
    nextMaintenanceDate: new Date(Date.now() + 20 * 86400000).toISOString(),
    description: 'Supplies compressed air to pneumatic tools across the workshop area.',
    isArchived: false,
    createdAt: '2021-02-28',
    updatedAt: '2023-09-01',
  },
  {
    id: 'm6',
    code: 'CD-11',
    name: 'Conveyor Drive',
    department: departmentName('d3'),
    departmentId: 'd3',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'CF-300',
    location: 'Bay 5',
    status: 'under_repair',
    installationDate: '2018-11-05',
    lastMaintenanceDate: '2023-04-10',
    nextMaintenanceDate: '2023-11-10',
    description: 'Main drive for raw material conveyor line.',
    isArchived: false,
    createdAt: '2018-11-05',
    updatedAt: '2023-10-05',
  },
  {
    id: 'm7',
    code: 'BFB-02',
    name: 'Blast Furnace Blower',
    department: departmentName('d6'),
    departmentId: 'd6',
    type: 'blower',
    manufacturer: 'ABB',
    model: 'BF-Air',
    location: 'Blast Furnace Area',
    status: 'active',
    installationDate: '2015-07-30',
    lastMaintenanceDate: '2023-08-01',
    nextMaintenanceDate: new Date(Date.now() + 90 * 86400000).toISOString(),
    description: 'Provides forced air draft to the blast furnace. Critical path asset.',
    isArchived: false,
    createdAt: '2015-07-30',
    updatedAt: '2023-08-01',
  },
  {
    id: 'm8',
    code: 'LM-15',
    name: 'Lathe Machine',
    department: departmentName('d19'),
    departmentId: 'd19',
    type: 'lathe',
    manufacturer: 'HMT',
    model: 'NH-22',
    location: 'Workshop Bay',
    status: 'active',
    installationDate: '2022-04-14',
    lastMaintenanceDate: '2023-09-15',
    nextMaintenanceDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    description: 'Precision heavy duty lathe used for machining large replacement shafts.',
    isArchived: false,
    createdAt: '2022-04-14',
    updatedAt: '2023-09-15',
  },
  {
    id: 'm9',
    code: 'PP-07',
    name: 'Pneumatic Press',
    department: departmentName('d19'),
    departmentId: 'd19',
    type: 'press',
    manufacturer: 'SMC',
    model: 'PN-200',
    location: 'Bay 4',
    status: 'inactive',
    installationDate: '2014-09-20',
    lastMaintenanceDate: '2022-11-01',
    nextMaintenanceDate: '2023-05-01',
    description: 'Standby pneumatic press for secondary forming operations.',
    isArchived: false,
    createdAt: '2014-09-20',
    updatedAt: '2023-01-10',
  },
  {
    id: 'm10',
    code: 'HT-09',
    name: 'Heat Treatment Furnace',
    department: departmentName('d18'),
    departmentId: 'd18',
    type: 'other',
    manufacturer: 'Inductotherm',
    model: 'HT-F1',
    location: 'QC Lab',
    status: 'active',
    installationDate: '2019-12-01',
    lastMaintenanceDate: '2023-07-20',
    nextMaintenanceDate: new Date(Date.now() + 75 * 86400000).toISOString(),
    description: 'Electric furnace for metallurgical testing and heat treatment.',
    isArchived: false,
    createdAt: '2019-12-01',
    updatedAt: '2023-07-20',
  },
  {
    id: 'm11',
    code: 'WP-03',
    name: 'Water Purification Unit',
    department: departmentName('d16'),
    departmentId: 'd16',
    type: 'other',
    manufacturer: 'Ion Exchange',
    model: 'RO-X',
    location: 'Water Plant',
    status: 'active',
    installationDate: '2020-07-15',
    lastMaintenanceDate: '2023-09-05',
    nextMaintenanceDate: new Date(Date.now() + 25 * 86400000).toISOString(),
    description: 'Reverse osmosis plant for boiler feed water preparation.',
    isArchived: false,
    createdAt: '2020-07-15',
    updatedAt: '2023-09-05',
  },
  {
    id: 'm12',
    code: 'EG-01',
    name: 'Emergency Generator',
    department: departmentName('d5'),
    departmentId: 'd5',
    type: 'other',
    manufacturer: 'Cummins',
    model: 'QSK-60',
    location: 'Power House',
    status: 'active',
    installationDate: '2018-03-10',
    lastMaintenanceDate: '2023-10-01',
    nextMaintenanceDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    description: '2.5 MW diesel generator for critical load backup.',
    isArchived: false,
    createdAt: '2018-03-10',
    updatedAt: '2023-10-01',
  },
  {
    id: 'm13',
    code: 'GM-06',
    name: 'Grinding Machine',
    department: departmentName('d19'),
    departmentId: 'd19',
    type: 'other',
    manufacturer: 'Schaudt',
    model: 'PF-50',
    location: 'Workshop Bay',
    status: 'active',
    installationDate: '2016-11-25',
    lastMaintenanceDate: '2023-02-15',
    nextMaintenanceDate: new Date(Date.now() - 10 * 86400000).toISOString(),
    description: 'Cylindrical grinder for finishing rolls.',
    isArchived: false,
    createdAt: '2016-11-25',
    updatedAt: '2023-02-15',
  },
  {
    id: 'm14',
    code: 'VP-14',
    name: 'Vacuum Pump',
    department: departmentName('d13'),
    departmentId: 'd13',
    type: 'pump',
    manufacturer: 'Leybold',
    model: 'SV-300',
    location: 'Rolling Mill Area',
    status: 'active',
    installationDate: '2021-09-08',
    lastMaintenanceDate: '2023-08-30',
    nextMaintenanceDate: new Date(Date.now() + 50 * 86400000).toISOString(),
    description: 'Vacuum extraction for primary rolling stand.',
    isArchived: false,
    createdAt: '2021-09-08',
    updatedAt: '2023-08-30',
  },
  {
    id: 'm15',
    code: 'CB-05',
    name: 'Circuit Breaker Panel',
    department: departmentName('d16'),
    departmentId: 'd16',
    type: 'other',
    manufacturer: 'ABB',
    model: 'VD4',
    location: 'Electrical Room',
    status: 'retired',
    installationDate: '2010-01-01',
    lastMaintenanceDate: '2022-01-15',
    nextMaintenanceDate: '2022-07-15',
    description: 'Decommissioned 11kV switchgear panel.',
    isArchived: true,
    createdAt: '2010-01-01',
    updatedAt: '2023-01-01',
  },
];

/**
 * Additional sample machines so every department has representative equipment.
 *
 * Equipment names follow integrated-steel-plant practice: a coke oven complex has
 * pushing, charging and quenching machines; a sinter plant has a travelling-grate
 * sinter machine, mixing drum and cooler; a rolling mill has a reheating furnace,
 * roughing and finishing stands, shears and a cooling bed.
 *
 * `m1`-`m15` above stay hand-written because tests reference them by id and code.
 * These use a compact seed table instead, since the shape repeats.
 */
interface MachineSeed {
  id: string;
  code: string;
  name: string;
  departmentId: string;
  type: MachineType;
  manufacturer: string;
  model: string;
  location: string;
  status: MachineStatus;
  installedOn: string;
  /** Days from now until the next service. Negative means already overdue. */
  dueInDays: number;
  description: string;
}

const additionalMachineSeeds: MachineSeed[] = [
  // Coke Ovens
  {
    id: 'm16',
    code: 'COB-PM-01',
    name: 'Coke Pusher Machine',
    departmentId: 'd1',
    type: 'other',
    manufacturer: 'Bhilai Engineering',
    model: 'CPM-7M',
    location: 'Battery 11 pusher side',
    status: 'active',
    installedOn: '2013-06-18',
    dueInDays: 12,
    description: 'Pushes coke from the oven chamber into the coke guide car.',
  },
  {
    id: 'm17',
    code: 'COB-CC-02',
    name: 'Coal Charging Car',
    departmentId: 'd1',
    type: 'other',
    manufacturer: 'Bhilai Engineering',
    model: 'CC-4H',
    location: 'Battery 9 oven top',
    status: 'active',
    installedOn: '2012-02-09',
    dueInDays: 40,
    description: 'Charges blended coal into oven chambers from the larry track.',
  },
  {
    id: 'm18',
    code: 'COB-QC-03',
    name: 'Quenching Car Locomotive',
    departmentId: 'd1',
    type: 'motor',
    manufacturer: 'Siemens',
    model: 'QL-90',
    location: 'Quenching tower approach',
    status: 'under_maintenance',
    installedOn: '2014-11-30',
    dueInDays: 6,
    description: 'Traction unit that moves the quenching car under the coke guide.',
  },
  {
    id: 'm19',
    code: 'COB-EX-04',
    name: 'Coke Oven Gas Exhauster',
    departmentId: 'd1',
    type: 'blower',
    manufacturer: 'Kirloskar',
    model: 'EX-1200',
    location: 'Gas exhauster house',
    status: 'active',
    installedOn: '2016-08-22',
    dueInDays: -8,
    description: 'Draws raw coke oven gas from the collecting main to gas treatment.',
  },

  // Coal Chemicals
  {
    id: 'm20',
    code: 'CC-TP-01',
    name: 'Tar Decanter Pump',
    departmentId: 'd2',
    type: 'pump',
    manufacturer: 'KSB',
    model: 'TD-160',
    location: 'Tar farm',
    status: 'active',
    installedOn: '2015-04-14',
    dueInDays: 22,
    description: 'Transfers decanted coal tar to storage.',
  },
  {
    id: 'm21',
    code: 'CC-AS-02',
    name: 'Ammonia Scrubber Fan',
    departmentId: 'd2',
    type: 'blower',
    manufacturer: 'Flowserve',
    model: 'AS-500',
    location: 'Scrubber bay',
    status: 'active',
    installedOn: '2017-01-25',
    dueInDays: 55,
    description: 'Maintains draft across the ammonia scrubbing column.',
  },
  {
    id: 'm22',
    code: 'CC-BP-03',
    name: 'Benzol Distillation Pump',
    departmentId: 'd2',
    type: 'pump',
    manufacturer: 'Grundfos',
    model: 'BD-90',
    location: 'Benzol plant',
    status: 'inactive',
    installedOn: '2011-09-03',
    dueInDays: -25,
    description: 'Standby feed pump for the benzol distillation column.',
  },

  // Sinter Plant 2
  {
    id: 'm23',
    code: 'SP2-SM-01',
    name: 'Sinter Machine Drive',
    departmentId: 'd4',
    type: 'motor',
    manufacturer: 'ABB',
    model: 'SMD-320',
    location: 'Sinter machine 1',
    status: 'active',
    installedOn: '2010-07-11',
    dueInDays: 9,
    description: 'Drives the travelling grate carrying the sinter mix.',
  },
  {
    id: 'm24',
    code: 'SP2-MD-02',
    name: 'Primary Mixing Drum',
    departmentId: 'd4',
    type: 'other',
    manufacturer: 'Metso',
    model: 'MD-4000',
    location: 'Mixing house',
    status: 'active',
    installedOn: '2012-12-01',
    dueInDays: 33,
    description: 'Blends ore fines, coke breeze, and flux before ignition.',
  },
  {
    id: 'm25',
    code: 'SP2-EF-03',
    name: 'ESP Exhaust Fan',
    departmentId: 'd4',
    type: 'blower',
    manufacturer: 'Kirloskar',
    model: 'EF-900',
    location: 'Gas cleaning plant',
    status: 'under_repair',
    installedOn: '2013-03-19',
    dueInDays: 4,
    description: 'Draws sinter waste gas through the electrostatic precipitator.',
  },
  {
    id: 'm26',
    code: 'SP2-SC-04',
    name: 'Sinter Cooler Drive',
    departmentId: 'd4',
    type: 'motor',
    manufacturer: 'Siemens',
    model: 'SC-210',
    location: 'Cooler bay',
    status: 'active',
    installedOn: '2015-10-08',
    dueInDays: 68,
    description: 'Rotates the circular cooler carrying hot sinter.',
  },

  // Steel Melting Shop 3
  {
    id: 'm27',
    code: 'SMS3-CV-01',
    name: 'Converter Tilting Drive',
    departmentId: 'd8',
    type: 'motor',
    manufacturer: 'Siemens',
    model: 'CTD-180T',
    location: 'Converter 1',
    status: 'active',
    installedOn: '2018-05-20',
    dueInDays: 14,
    description: 'Tilts the 180 tonne basic oxygen converter for charging and tapping.',
  },
  {
    id: 'm28',
    code: 'SMS3-LF-02',
    name: 'Ladle Furnace Electrode Mast',
    departmentId: 'd8',
    type: 'other',
    manufacturer: 'Danieli',
    model: 'LF-3E',
    location: 'Secondary refining bay',
    status: 'active',
    installedOn: '2018-06-14',
    dueInDays: 30,
    description: 'Raises and lowers graphite electrodes during ladle refining.',
  },
  {
    id: 'm29',
    code: 'SMS3-RH-03',
    name: 'RH Degasser Vacuum Pump',
    departmentId: 'd8',
    type: 'pump',
    manufacturer: 'Leybold',
    model: 'RH-VP800',
    location: 'RH degasser',
    status: 'under_maintenance',
    installedOn: '2018-07-02',
    dueInDays: 3,
    description: 'Creates vacuum for hydrogen removal in the RH degasser.',
  },
  {
    id: 'm30',
    code: 'SMS3-CR-04',
    name: 'Hot Metal Charging Crane',
    departmentId: 'd8',
    type: 'crane',
    manufacturer: 'Demag',
    model: 'HMC-300T',
    location: 'Charging aisle',
    status: 'active',
    installedOn: '2018-04-11',
    dueInDays: 47,
    description: '300 tonne crane lifting hot metal ladles to the converter.',
  },

  // Continuous Casting Shop
  {
    id: 'm31',
    code: 'CCS-MO-01',
    name: 'Billet Caster Mould Oscillator',
    departmentId: 'd9',
    type: 'other',
    manufacturer: 'Danieli',
    model: 'MO-120',
    location: 'Billet caster 1',
    status: 'active',
    installedOn: '2018-09-15',
    dueInDays: 11,
    description: 'Oscillates the mould to prevent strand sticking during casting.',
  },
  {
    id: 'm32',
    code: 'CCS-WU-02',
    name: 'Bloom Withdrawal Unit',
    departmentId: 'd9',
    type: 'motor',
    manufacturer: 'SMS Group',
    model: 'WU-450',
    location: 'Bloom caster',
    status: 'active',
    installedOn: '2018-10-02',
    dueInDays: 26,
    description: 'Withdraws and straightens the solidifying bloom strand.',
  },
  {
    id: 'm33',
    code: 'CCS-TC-03',
    name: 'Tundish Transfer Car',
    departmentId: 'd9',
    type: 'other',
    manufacturer: 'Danieli',
    model: 'TC-60',
    location: 'Casting floor',
    status: 'active',
    installedOn: '2019-01-28',
    dueInDays: -3,
    description: 'Moves preheated tundishes into the casting position.',
  },

  // Universal Rail Mill
  {
    id: 'm34',
    code: 'URM-UR-01',
    name: 'Universal Roughing Stand',
    departmentId: 'd11',
    type: 'mill',
    manufacturer: 'SMS Meer',
    model: 'UR-1000',
    location: 'URM roughing line',
    status: 'active',
    installedOn: '2017-03-30',
    dueInDays: 8,
    description: 'First universal stand shaping the rail profile.',
  },
  {
    id: 'm35',
    code: 'URM-HH-02',
    name: 'Rail Head Hardening Unit',
    departmentId: 'd11',
    type: 'other',
    manufacturer: 'SMS Meer',
    model: 'HH-260',
    location: 'URM finishing line',
    status: 'active',
    installedOn: '2019-07-16',
    dueInDays: 35,
    description: 'Online head hardening for R260 grade rails.',
  },
  {
    id: 'm36',
    code: 'URM-EC-03',
    name: 'Eddy Current Testing Machine',
    departmentId: 'd11',
    type: 'other',
    manufacturer: 'Olympus',
    model: 'EC-130',
    location: 'URM inspection bay',
    status: 'active',
    installedOn: '2017-08-09',
    dueInDays: 60,
    description: 'Online surface defect detection for 130 metre rails.',
  },
  {
    id: 'm37',
    code: 'URM-RC-04',
    name: 'Long Rail Handling Crane',
    departmentId: 'd11',
    type: 'crane',
    manufacturer: 'Demag',
    model: 'LRC-40T',
    location: 'Rail despatch yard',
    status: 'inactive',
    installedOn: '2017-11-21',
    dueInDays: -14,
    description: 'Handles welded rail panels up to 260 metres.',
  },

  // Merchant Mill
  {
    id: 'm38',
    code: 'MM-RF-01',
    name: 'Billet Reheating Furnace',
    departmentId: 'd12',
    type: 'other',
    manufacturer: 'Tenova',
    model: 'RF-1250',
    location: 'MM furnace bay',
    status: 'active',
    installedOn: '2009-02-17',
    dueInDays: 13,
    description: 'Heats billets to uniform rolling temperature.',
  },
  {
    id: 'm39',
    code: 'MM-RS-02',
    name: 'Roughing Stand Drive',
    departmentId: 'd12',
    type: 'mill',
    manufacturer: 'Flender',
    model: 'RS-650',
    location: 'MM roughing train',
    status: 'active',
    installedOn: '2009-04-05',
    dueInDays: 28,
    description: 'Drives the roughing stands for light structurals and rounds.',
  },
  {
    id: 'm40',
    code: 'MM-CS-03',
    name: 'Crop Shear',
    departmentId: 'd12',
    type: 'press',
    manufacturer: 'SMS Meer',
    model: 'CS-400',
    location: 'MM shear line',
    status: 'active',
    installedOn: '2010-01-19',
    dueInDays: 52,
    description: 'Crops head and tail ends of the rolled bar.',
  },
  {
    id: 'm41',
    code: 'MM-CB-04',
    name: 'Cooling Bed Transfer Drive',
    departmentId: 'd12',
    type: 'conveyor',
    manufacturer: 'Siemens',
    model: 'CB-300',
    location: 'MM cooling bed',
    status: 'under_repair',
    installedOn: '2010-05-23',
    dueInDays: 5,
    description: 'Transfers rolled sections across the cooling bed.',
  },

  // Bar & Rod Mill
  {
    id: 'm42',
    code: 'BRM-WB-01',
    name: 'Walking Beam Furnace',
    departmentId: 'd14',
    type: 'other',
    manufacturer: 'Tenova',
    model: 'WB-160',
    location: 'BRM furnace bay',
    status: 'active',
    installedOn: '2018-02-27',
    dueInDays: 10,
    description: 'Fully automatic walking beam reheating furnace.',
  },
  {
    id: 'm43',
    code: 'BRM-BM-02',
    name: 'Wire Rod Block Mill',
    departmentId: 'd14',
    type: 'mill',
    manufacturer: 'Morgan',
    model: 'BM-10',
    location: 'BRM finishing block',
    status: 'active',
    installedOn: '2018-03-15',
    dueInDays: 24,
    description: 'High speed finishing block for 5.5 to 20 mm product.',
  },
  {
    id: 'm44',
    code: 'BRM-QB-03',
    name: 'TMT Quenching Box',
    departmentId: 'd14',
    type: 'other',
    manufacturer: 'Danieli',
    model: 'QB-60',
    location: 'BRM quench line',
    status: 'active',
    installedOn: '2018-04-08',
    dueInDays: 44,
    description: 'Controlled quenching for TMT rebar.',
  },
  {
    id: 'm45',
    code: 'BRM-CL-04',
    name: 'Coil Handling Conveyor',
    departmentId: 'd14',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'CL-220',
    location: 'BRM coil yard',
    status: 'active',
    installedOn: '2018-06-30',
    dueInDays: -6,
    description: 'Moves finished coils to the binding and despatch area.',
  },

  // Slag Granulation Plant
  {
    id: 'm46',
    code: 'SGP-GP-01',
    name: 'Slag Granulation Pump',
    departmentId: 'd20',
    type: 'pump',
    manufacturer: 'KSB',
    model: 'GP-450',
    location: 'Granulation pit',
    status: 'active',
    installedOn: '2016-05-12',
    dueInDays: 7,
    description: 'High volume water pump for blast furnace slag granulation.',
  },
  {
    id: 'm47',
    code: 'SGP-DD-02',
    name: 'Dewatering Drum',
    departmentId: 'd20',
    type: 'other',
    manufacturer: 'Metso',
    model: 'DD-300',
    location: 'Dewatering bay',
    status: 'active',
    installedOn: '2016-06-20',
    dueInDays: 38,
    description: 'Separates granulated slag from process water.',
  },
  {
    id: 'm48',
    code: 'SGP-SB-03',
    name: 'Granulated Slag Conveyor',
    departmentId: 'd20',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'SB-800',
    location: 'Slag despatch',
    status: 'under_maintenance',
    installedOn: '2016-08-04',
    dueInDays: 2,
    description: 'Belt conveyor feeding the granulated slag stockpile.',
  },

  // Traffic & Material Handling
  {
    id: 'm49',
    code: 'TMH-WT-01',
    name: 'Wagon Tippler',
    departmentId: 'd21',
    type: 'other',
    manufacturer: 'Bhilai Engineering',
    model: 'WT-2',
    location: 'Tippler house 1',
    status: 'active',
    installedOn: '2011-10-14',
    dueInDays: 15,
    description: 'Unloads incoming ore and coal wagons into track hoppers.',
  },
  {
    id: 'm50',
    code: 'TMH-SR-02',
    name: 'Stacker Reclaimer',
    departmentId: 'd21',
    type: 'other',
    manufacturer: 'ThyssenKrupp',
    model: 'SR-1500',
    location: 'Ore bedding yard',
    status: 'active',
    installedOn: '2012-07-08',
    dueInDays: 29,
    description: 'Stacks and reclaims raw material in the blending yard.',
  },
  {
    id: 'm51',
    code: 'TMH-SL-03',
    name: 'Diesel Shunting Locomotive',
    departmentId: 'd21',
    type: 'motor',
    manufacturer: 'CLW',
    model: 'SL-1400',
    location: 'Marshalling yard',
    status: 'active',
    installedOn: '2014-01-22',
    dueInDays: 63,
    description: 'Shunts wagon rakes between the yard and unloading points.',
  },
  {
    id: 'm52',
    code: 'TMH-TH-04',
    name: 'Track Hopper Conveyor',
    departmentId: 'd21',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'TH-1200',
    location: 'Track hopper 2',
    status: 'under_repair',
    installedOn: '2011-12-05',
    dueInDays: -11,
    description: 'Withdraws material from the track hopper to the bedding yard.',
  },
  // Coal Handling — the Supervisor's department, so it needs a workable sample.
  {
    id: 'm53',
    code: 'CHM-CB-05',
    name: 'Coal Yard Belt Conveyor',
    departmentId: 'd3',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'CB-1400',
    location: 'Coal yard belt 5',
    status: 'active',
    installedOn: '2013-08-19',
    dueInDays: 13,
    description: 'Main coal yard belt feeding the coke oven coal tower.',
  },
  {
    id: 'm54',
    code: 'CHM-CR-06',
    name: 'Coal Crusher',
    departmentId: 'd3',
    type: 'other',
    manufacturer: 'Metso',
    model: 'CR-900',
    location: 'Crusher house',
    status: 'active',
    installedOn: '2014-03-27',
    dueInDays: 31,
    description: 'Reduces run-of-mine coal to charging size.',
  },
  {
    id: 'm55',
    code: 'CHM-SC-07',
    name: 'Vibrating Screen',
    departmentId: 'd3',
    type: 'other',
    manufacturer: 'Metso',
    model: 'SC-250',
    location: 'Screening house',
    status: 'under_maintenance',
    installedOn: '2015-05-11',
    dueInDays: 4,
    description: 'Screens crushed coal ahead of the blending bunkers.',
  },
  {
    id: 'm56',
    code: 'CHM-DP-08',
    name: 'Dust Suppression Pump',
    departmentId: 'd3',
    type: 'pump',
    manufacturer: 'KSB',
    model: 'DP-120',
    location: 'Coal yard',
    status: 'active',
    installedOn: '2017-02-08',
    dueInDays: -9,
    description: 'Supplies water spray for coal yard dust suppression.',
  },

  // Sinter Plant 3
  {
    id: 'm57',
    code: 'SP3-SM-05',
    name: 'Sinter Machine 2 Drive',
    departmentId: 'd5',
    type: 'motor',
    manufacturer: 'ABB',
    model: 'SMD-360',
    location: 'Sinter machine 2',
    status: 'active',
    installedOn: '2019-04-16',
    dueInDays: 10,
    description: 'Drive for the 360 sq.m MODEX sinter machine.',
  },
  {
    id: 'm58',
    code: 'SP3-IF-06',
    name: 'Ignition Furnace',
    departmentId: 'd5',
    type: 'other',
    manufacturer: 'Tenova',
    model: 'IF-360',
    location: 'Sinter machine 2 head',
    status: 'active',
    installedOn: '2019-05-02',
    dueInDays: 27,
    description: 'Ignites the surface of the sinter mix on the grate.',
  },
  {
    id: 'm59',
    code: 'SP3-RF-07',
    name: 'Return Fines Conveyor',
    departmentId: 'd5',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'RF-700',
    location: 'Return fines circuit',
    status: 'active',
    installedOn: '2019-06-25',
    dueInDays: 49,
    description: 'Returns undersize sinter to the mixing circuit.',
  },

  // Blast Furnaces
  {
    id: 'm60',
    code: 'BF-CH-03',
    name: 'Coneless Top Charging Device',
    departmentId: 'd6',
    type: 'other',
    manufacturer: 'Paul Wurth',
    model: 'BLT-4060',
    location: 'Blast Furnace 8 top',
    status: 'active',
    installedOn: '2018-08-14',
    dueInDays: 16,
    description: 'Chute-type charging device giving uniform burden distribution.',
  },
  {
    id: 'm61',
    code: 'BF-HS-04',
    name: 'Hot Blast Stove Valve Drive',
    departmentId: 'd6',
    type: 'other',
    manufacturer: 'Paul Wurth',
    model: 'HS-3',
    location: 'BF 8 stove house',
    status: 'active',
    installedOn: '2018-08-30',
    dueInDays: 34,
    description: 'Operates changeover valves between the hot blast stoves.',
  },
  {
    id: 'm62',
    code: 'BF-PCI-05',
    name: 'Pulverised Coal Injection Blower',
    departmentId: 'd6',
    type: 'blower',
    manufacturer: 'Atlas Copco',
    model: 'PCI-600',
    location: 'BF 8 PCI plant',
    status: 'under_repair',
    installedOn: '2018-09-21',
    dueInDays: 3,
    description: 'Conveys pulverised coal to the tuyeres for injection.',
  },
  {
    id: 'm63',
    code: 'BF-TRT-06',
    name: 'Top Pressure Recovery Turbine',
    departmentId: 'd6',
    type: 'other',
    manufacturer: 'Siemens',
    model: 'TRT-14',
    location: 'BF 8 gas line',
    status: 'active',
    installedOn: '2018-10-09',
    dueInDays: 72,
    description: 'Recovers energy from blast furnace top gas pressure.',
  },

  // Plate Mill
  {
    id: 'm64',
    code: 'PM-RF-02',
    name: 'Slab Reheating Furnace',
    departmentId: 'd15',
    type: 'other',
    manufacturer: 'Tenova',
    model: 'RF-3270',
    location: 'Plate Mill furnace bay',
    status: 'active',
    installedOn: '2008-11-12',
    dueInDays: 18,
    description: 'Heats continuously cast slabs for plate rolling.',
  },
  {
    id: 'm65',
    code: 'PM-DS-03',
    name: 'High Pressure Descaler',
    departmentId: 'd15',
    type: 'pump',
    manufacturer: 'KSB',
    model: 'DS-400',
    location: 'Plate Mill entry',
    status: 'active',
    installedOn: '2009-01-30',
    dueInDays: 25,
    description: 'Removes scale from the heated slab before rolling.',
  },
  {
    id: 'm66',
    code: 'PM-NF-04',
    name: 'Roller Hearth Normalising Furnace',
    departmentId: 'd15',
    type: 'other',
    manufacturer: 'Tenova',
    model: 'NF-120',
    location: 'Plate finishing line',
    status: 'active',
    installedOn: '2010-06-07',
    dueInDays: -4,
    description: 'Offline normalising of plates to customer specification.',
  },
  {
    id: 'm67',
    code: 'PM-UT-05',
    name: 'Online Ultrasonic Testing Machine',
    departmentId: 'd15',
    type: 'other',
    manufacturer: 'Olympus',
    model: 'UT-320',
    location: 'Plate inspection line',
    status: 'active',
    installedOn: '2011-03-18',
    dueInDays: 58,
    description: 'Online ultrasonic inspection of finished plate.',
  },

  // Steel Melting Shop 2
  {
    id: 'm68',
    code: 'SMS2-CV-02',
    name: 'Converter 2 Tilting Drive',
    departmentId: 'd7',
    type: 'motor',
    manufacturer: 'Siemens',
    model: 'CTD-130T',
    location: 'SMS2 converter 2',
    status: 'active',
    installedOn: '2007-05-24',
    dueInDays: 20,
    description: 'Tilts the 110/130 tonne LD converter.',
  },
  {
    id: 'm69',
    code: 'SMS2-DS-03',
    name: 'Hot Metal Desulphurisation Unit',
    departmentId: 'd7',
    type: 'other',
    manufacturer: 'Danieli',
    model: 'DS-140',
    location: 'SMS2 hot metal bay',
    status: 'active',
    installedOn: '2016-11-15',
    dueInDays: 42,
    description: 'Injects reagent to desulphurise hot metal before blowing.',
  },
  {
    id: 'm70',
    code: 'SMS2-VAD-04',
    name: 'VAD Vacuum Pump',
    departmentId: 'd7',
    type: 'pump',
    manufacturer: 'Leybold',
    model: 'VAD-600',
    location: 'SMS2 refining bay',
    status: 'inactive',
    installedOn: '2006-09-08',
    dueInDays: -30,
    description: 'Vacuum arc degassing pump, standby unit.',
  },

  // Rail & Structural Mill
  {
    id: 'm71',
    code: 'RSM-RF-02',
    name: 'Bloom Reheating Furnace',
    departmentId: 'd10',
    type: 'other',
    manufacturer: 'Tenova',
    model: 'RF-880',
    location: 'RSM furnace bay',
    status: 'active',
    installedOn: '2005-04-19',
    dueInDays: 17,
    description: 'Heats blooms for rail and structural rolling.',
  },
  {
    id: 'm72',
    code: 'RSM-SS-03',
    name: 'Rail Straightening Press',
    departmentId: 'd10',
    type: 'press',
    manufacturer: 'SMS Meer',
    model: 'SS-900',
    location: 'RSM finishing line',
    status: 'active',
    installedOn: '2006-02-11',
    dueInDays: 39,
    description: 'Laser controlled press straightening rolled rails.',
  },
  {
    id: 'm73',
    code: 'RSM-CB-04',
    name: 'Cooling Bed Drive',
    departmentId: 'd10',
    type: 'conveyor',
    manufacturer: 'Flender',
    model: 'CB-450',
    location: 'RSM cooling bed',
    status: 'active',
    installedOn: '2006-08-03',
    dueInDays: 66,
    description: 'Moves rolled sections across the RSM cooling bed.',
  },

  // Wire Rod Mill
  {
    id: 'm74',
    code: 'WRM-BM-02',
    name: 'Finishing Block Mill',
    departmentId: 'd13',
    type: 'mill',
    manufacturer: 'Morgan',
    model: 'BM-8',
    location: 'WRM finishing block',
    status: 'active',
    installedOn: '2008-07-22',
    dueInDays: 12,
    description: 'High speed block rolling 5.5 to 8 mm plain wire rod.',
  },
  {
    id: 'm75',
    code: 'WRM-LH-03',
    name: 'Laying Head',
    departmentId: 'd13',
    type: 'other',
    manufacturer: 'Morgan',
    model: 'LH-140',
    location: 'WRM coiling line',
    status: 'active',
    installedOn: '2008-09-14',
    dueInDays: 36,
    description: 'Forms rod coils onto the Stelmor cooling conveyor.',
  },

  // Oxygen Plants
  {
    id: 'm76',
    code: 'OP-ASU-02',
    name: 'Air Separation Unit Compressor',
    departmentId: 'd17',
    type: 'compressor',
    manufacturer: 'Atlas Copco',
    model: 'ASU-2400',
    location: 'Oxygen Plant 2',
    status: 'active',
    installedOn: '2015-12-03',
    dueInDays: 21,
    description: 'Main air compressor feeding the air separation column.',
  },
  {
    id: 'm77',
    code: 'OP-LP-03',
    name: 'Liquid Oxygen Transfer Pump',
    departmentId: 'd17',
    type: 'pump',
    manufacturer: 'Cryostar',
    model: 'LP-90',
    location: 'LOX storage',
    status: 'active',
    installedOn: '2016-04-27',
    dueInDays: 48,
    description: 'Transfers liquid oxygen to storage and filling bays.',
  },

  // Refractory Materials Plant
  {
    id: 'm78',
    code: 'RMP-KL-02',
    name: 'Lime Kiln 3 Drive',
    departmentId: 'd18',
    type: 'motor',
    manufacturer: 'ABB',
    model: 'KL-450',
    location: 'RMP 3 kiln 3',
    status: 'active',
    installedOn: '2017-06-15',
    dueInDays: 14,
    description: 'Rotates the 450 tonne per day gas fired lime kiln.',
  },
  {
    id: 'm79',
    code: 'RMP-DC-03',
    name: 'Dolomite Crusher',
    departmentId: 'd18',
    type: 'other',
    manufacturer: 'Metso',
    model: 'DC-320',
    location: 'RMP raw material bay',
    status: 'active',
    installedOn: '2017-08-08',
    dueInDays: 43,
    description: 'Crushes raw dolomite ahead of calcination.',
  },
];

function buildMachine(seed: MachineSeed): Machine {
  const installedAt = new Date(seed.installedOn).toISOString();
  return {
    id: seed.id,
    code: seed.code,
    name: seed.name,
    department: departmentName(seed.departmentId),
    departmentId: seed.departmentId,
    type: seed.type,
    manufacturer: seed.manufacturer,
    model: seed.model,
    location: seed.location,
    status: seed.status,
    installationDate: seed.installedOn,
    lastMaintenanceDate: '',
    nextMaintenanceDate: new Date(Date.now() + seed.dueInDays * 86400000).toISOString(),
    description: seed.description,
    isArchived: false,
    createdAt: installedAt,
    updatedAt: installedAt,
  };
}

mockMachines.push(...additionalMachineSeeds.map(buildMachine));

syncDepartmentMachineCounts();

/**
 * Maintenance records, seeded compactly like machines and parts.
 *
 * `daysFromNow` drives `scheduledDate` so overdue/due-soon/ok examples exist relative
 * to whenever fixtures load, matching the 15-day window in `maintenance-window.ts`.
 * `status: 'overdue'` does not exist — overdue is derived from `scheduledDate`, never
 * stored (decision 2026-07-26).
 */
interface MaintenanceRecordSeed {
  id: string;
  machineId: string;
  type: MaintenanceType;
  status: MaintenanceStatus;
  daysFromNow: number;
  /** Only meaningful when status is 'completed'; days from now, normally negative. */
  completedDaysFromNow?: number;
  technicianId: string;
  technicianName: string;
  description: string;
  findings?: string;
  actions?: string;
  partsUsed?: string;
  durationHours?: number;
  remarks?: string;
}

const maintenanceRecordSeeds: MaintenanceRecordSeed[] = [
  {
    id: 'mr1',
    machineId: 'm1',
    type: 'preventive',
    status: 'scheduled',
    daysFromNow: 15,
    technicianId: 't1',
    technicianName: 'R. Kumar',
    description: 'Monthly fluid check and filter replacement.',
  },
  {
    id: 'mr2',
    machineId: 'm2',
    type: 'corrective',
    status: 'in_progress',
    daysFromNow: -2,
    technicianId: 't2',
    technicianName: 'S. Sharma',
    description: 'Replace worn bearings on drive shaft.',
    findings: 'Drive-end bearing showing early spalling.',
  },
  {
    id: 'mr3',
    machineId: 'm3',
    type: 'lubrication',
    status: 'completed',
    daysFromNow: -40,
    completedDaysFromNow: -39,
    technicianId: 't3',
    technicianName: 'A. Patel',
    description: 'Grease bearings and check seal integrity.',
    actions: 'Regreased both bearings; seal within tolerance.',
    durationHours: 4,
  },
  {
    id: 'mr4',
    machineId: 'm13',
    type: 'calibration',
    status: 'scheduled',
    daysFromNow: -10,
    technicianId: 't4',
    technicianName: 'M. Singh',
    description: 'Annual precision calibration.',
  },
  {
    id: 'mr5',
    machineId: 'm7',
    type: 'inspection',
    status: 'completed',
    daysFromNow: -20,
    completedDaysFromNow: -20,
    technicianId: 't5',
    technicianName: 'T. Das',
    description: 'Vibration analysis.',
    actions: 'Within normal range; no action required.',
    durationHours: 2,
  },
  {
    id: 'mr6',
    machineId: 'm6',
    type: 'corrective',
    status: 'scheduled',
    daysFromNow: 3,
    technicianId: 't2',
    technicianName: 'S. Sharma',
    description: 'Inspect gearbox after unscheduled replacement.',
    partsUsed: 'GB450-9021 gearbox assembly',
  },
  {
    id: 'mr7',
    machineId: 'm16',
    type: 'preventive',
    status: 'scheduled',
    daysFromNow: 12,
    technicianId: 't1',
    technicianName: 'R. Kumar',
    description: 'Pusher ram shoe wear check.',
  },
  {
    id: 'mr8',
    machineId: 'm23',
    type: 'inspection',
    status: 'in_progress',
    daysFromNow: -1,
    technicianId: 't4',
    technicianName: 'M. Singh',
    description: 'Sinter machine drive gearbox inspection ahead of life expiry.',
  },
  {
    id: 'mr9',
    machineId: 'm27',
    type: 'preventive',
    status: 'completed',
    daysFromNow: -60,
    completedDaysFromNow: -58,
    technicianId: 't5',
    technicianName: 'T. Das',
    description: 'Converter tilting drive service.',
    actions: 'Replaced brake lining set; re-torqued pinion mounts.',
    durationHours: 6,
  },
  {
    id: 'mr10',
    machineId: 'm53',
    type: 'lubrication',
    status: 'scheduled',
    daysFromNow: 8,
    technicianId: 't3',
    technicianName: 'A. Patel',
    description: 'Idler roller lubrication round.',
  },
  {
    id: 'mr11',
    machineId: 'm64',
    type: 'calibration',
    status: 'cancelled',
    daysFromNow: -15,
    technicianId: 't4',
    technicianName: 'M. Singh',
    description: 'Thermocouple recalibration.',
    remarks: 'Deferred to next planned shutdown.',
  },
  {
    id: 'mr12',
    machineId: 'm9',
    type: 'emergency',
    status: 'completed',
    daysFromNow: -95,
    completedDaysFromNow: -95,
    technicianId: 't2',
    technicianName: 'S. Sharma',
    description: 'Unscheduled stop after abnormal vibration.',
    findings: 'Loose foundation bolt.',
    actions: 'Re-torqued foundation bolts and re-aligned.',
    durationHours: 3,
  },
];

function daysFromNow(days: number): string {
  return new Date(Date.now() + days * 86400000).toISOString();
}

function buildMaintenanceRecord(seed: MaintenanceRecordSeed): MaintenanceRecord {
  const machine = mockMachines.find((candidate) => candidate.id === seed.machineId);
  const scheduledDate = daysFromNow(seed.daysFromNow);
  const completedDate =
    seed.status === 'completed' && seed.completedDaysFromNow !== undefined
      ? daysFromNow(seed.completedDaysFromNow)
      : undefined;
  const createdAt = scheduledDate;
  const updatedAt = completedDate ?? scheduledDate;

  return {
    id: seed.id,
    machineId: seed.machineId,
    machineName: machine?.name ?? 'Unknown machine',
    machineCode: machine?.code ?? '—',
    type: seed.type,
    status: seed.status,
    scheduledDate,
    completedDate,
    technicianId: seed.technicianId,
    technicianName: seed.technicianName,
    description: seed.description,
    findings: seed.findings,
    actions: seed.actions,
    partsUsed: seed.partsUsed,
    durationHours: seed.durationHours,
    remarks: seed.remarks,
    createdAt,
    updatedAt,
  };
}

export const mockMaintenanceRecords: MaintenanceRecord[] =
  maintenanceRecordSeeds.map(buildMaintenanceRecord);

interface MaintenancePlanSeed {
  id: string;
  machineId: string;
  type: MaintenanceType;
  description: string;
  intervalValue: number;
  intervalUnit: RecurrenceUnit;
  technicianId?: string;
  technicianName?: string;
  isActive: boolean;
  /** Days ago the plan was last completed; omit if never completed. */
  lastCompletedDaysAgo?: number;
  /** Days ago the plan was created. */
  createdDaysAgo: number;
}

const maintenancePlanSeeds: MaintenancePlanSeed[] = [
  {
    id: 'plan1',
    machineId: 'm1',
    type: 'preventive',
    description: 'Monthly hydraulic fluid and filter check.',
    intervalValue: 1,
    intervalUnit: 'months',
    technicianId: 't1',
    technicianName: 'R. Kumar',
    isActive: true,
    lastCompletedDaysAgo: 20,
    createdDaysAgo: 400,
  },
  {
    id: 'plan2',
    machineId: 'm2',
    type: 'lubrication',
    description: 'Quarterly bearing lubrication.',
    intervalValue: 3,
    intervalUnit: 'months',
    technicianId: 't2',
    technicianName: 'S. Sharma',
    isActive: true,
    lastCompletedDaysAgo: 88,
    createdDaysAgo: 600,
  },
  {
    id: 'plan3',
    machineId: 'm7',
    type: 'inspection',
    description: 'Semi-annual vibration analysis.',
    intervalValue: 6,
    intervalUnit: 'months',
    technicianId: 't5',
    technicianName: 'T. Das',
    isActive: true,
    lastCompletedDaysAgo: 20,
    createdDaysAgo: 900,
  },
  {
    id: 'plan4',
    machineId: 'm23',
    type: 'calibration',
    description: 'Annual gearbox inspection.',
    intervalValue: 1,
    intervalUnit: 'years',
    isActive: true,
    createdDaysAgo: 340,
  },
  {
    id: 'plan5',
    machineId: 'm53',
    type: 'lubrication',
    description: 'Idler roller lubrication round.',
    intervalValue: 2,
    intervalUnit: 'weeks',
    technicianId: 't3',
    technicianName: 'A. Patel',
    isActive: true,
    lastCompletedDaysAgo: 6,
    createdDaysAgo: 200,
  },
  {
    id: 'plan6',
    machineId: 'm9',
    type: 'preventive',
    description: 'Retired standby press; plan kept for history.',
    intervalValue: 1,
    intervalUnit: 'years',
    isActive: false,
    lastCompletedDaysAgo: 95,
    createdDaysAgo: 700,
  },
];

function buildMaintenancePlan(seed: MaintenancePlanSeed): MaintenancePlan {
  const machine = mockMachines.find((candidate) => candidate.id === seed.machineId);
  const createdAt = daysFromNow(-seed.createdDaysAgo);
  const lastCompletedDate =
    seed.lastCompletedDaysAgo !== undefined ? daysFromNow(-seed.lastCompletedDaysAgo) : undefined;

  return {
    id: seed.id,
    machineId: seed.machineId,
    machineName: machine?.name ?? 'Unknown machine',
    machineCode: machine?.code ?? '—',
    type: seed.type,
    description: seed.description,
    intervalValue: seed.intervalValue,
    intervalUnit: seed.intervalUnit,
    technicianId: seed.technicianId,
    technicianName: seed.technicianName,
    isActive: seed.isActive,
    isArchived: false,
    lastCompletedDate,
    createdAt,
    updatedAt: lastCompletedDate ?? createdAt,
  };
}

export const mockMaintenancePlans: MaintenancePlan[] =
  maintenancePlanSeeds.map(buildMaintenancePlan);

export const mockRepairRecords: RepairRecord[] = [
  {
    id: 'rr1',
    machineId: 'm6',
    machineCode: 'CD-11',
    machineName: 'Conveyor Drive',
    status: 'in_progress',
    reportedDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    startDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    reportedBy: 'Operator',
    assignedTo: 'B. Nair',
    description: 'Drive motor making abnormal grinding noise',
    diagnosis: 'Gearbox failure due to overload',
    partsUsed: 'Gearbox assembly',
    downtimeHours: 28,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'rr2',
    machineId: 'm4',
    machineCode: 'OC-03',
    machineName: 'Overhead Crane',
    status: 'waiting_for_parts',
    reportedDate: new Date(Date.now() - 10 * 86400000).toISOString(),
    reportedBy: 'Shift Supervisor',
    assignedTo: 'R. Kumar',
    description: 'Pendant control unresponsive intermittently',
    diagnosis: 'Faulty control cable',
    partsUsed: 'Pendant control cable',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'rr3',
    machineId: 'm5',
    machineCode: 'AC-06',
    machineName: 'Air Compressor',
    status: 'completed',
    reportedDate: new Date(Date.now() - 30 * 86400000).toISOString(),
    startDate: new Date(Date.now() - 29 * 86400000).toISOString(),
    completedDate: new Date(Date.now() - 28 * 86400000).toISOString(),
    reportedBy: 'Maintenance',
    assignedTo: 'M. Singh',
    description: 'Pressure drop in main line',
    diagnosis: 'Blown safety valve',
    resolution: 'Replaced safety valve and tested',
    downtimeHours: 12,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
];

/**
 * Installed components fitted to machines.
 *
 * Seeded compactly because the shape repeats. `machineName` and `machineCode` are
 * denormalized for display and resolved from the machine fixtures so they cannot drift.
 */
interface PartSeed {
  id: string;
  machineId: string;
  partCode: string;
  partName: string;
  category: string;
  serialNumber?: string;
  quantity: number;
  unit: string;
  positionOnMachine: string;
  /** Months before now that the component was fitted. */
  fittedMonthsAgo: number;
  expectedLifeMonths?: number;
  notes?: string;
}

const partSeeds: PartSeed[] = [
  // Hydraulic Press, Plate Mill
  {
    id: 'p1',
    machineId: 'm1',
    partCode: 'HF-220',
    partName: 'Hydraulic Filter Element',
    category: 'Hydraulics',
    serialNumber: 'HF220-8891',
    quantity: 2,
    unit: 'pcs',
    positionOnMachine: 'Main pump manifold',
    fittedMonthsAgo: 10,
    expectedLifeMonths: 12,
    notes: 'Differential pressure indicator fitted.',
  },
  {
    id: 'p2',
    machineId: 'm1',
    partCode: 'SL-118',
    partName: 'Cylinder Rod Seal',
    category: 'Seals',
    serialNumber: 'SL118-4402',
    quantity: 4,
    unit: 'pcs',
    positionOnMachine: 'Main ram cylinder',
    fittedMonthsAgo: 26,
    expectedLifeMonths: 24,
  },
  {
    id: 'p3',
    machineId: 'm1',
    partCode: 'PG-050',
    partName: 'Pressure Gauge',
    category: 'Instrumentation',
    quantity: 3,
    unit: 'pcs',
    positionOnMachine: 'Control panel',
    fittedMonthsAgo: 4,
  },

  // Rolling Mill Motor, RSM
  {
    id: 'p4',
    machineId: 'm2',
    partCode: 'BR-600',
    partName: 'Drive End Bearing',
    category: 'Bearings',
    serialNumber: 'BR600-2231',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Drive end housing',
    fittedMonthsAgo: 18,
    expectedLifeMonths: 18,
    notes: 'SKF spherical roller, SNL housing.',
  },
  {
    id: 'p5',
    machineId: 'm2',
    partCode: 'BR-601',
    partName: 'Non-Drive End Bearing',
    category: 'Bearings',
    serialNumber: 'BR601-2232',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Non-drive end housing',
    fittedMonthsAgo: 18,
    expectedLifeMonths: 18,
  },
  {
    id: 'p6',
    machineId: 'm2',
    partCode: 'CB-330',
    partName: 'Carbon Brush Set',
    category: 'Electrical',
    quantity: 8,
    unit: 'set',
    positionOnMachine: 'Commutator end',
    fittedMonthsAgo: 5,
    expectedLifeMonths: 9,
  },

  // Cooling Water Pump, Power Plants
  {
    id: 'p7',
    machineId: 'm3',
    partCode: 'MS-100',
    partName: 'Mechanical Seal',
    category: 'Seals',
    serialNumber: 'MS100-7710',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Pump stuffing box',
    fittedMonthsAgo: 30,
    expectedLifeMonths: 24,
    notes: 'Slight weepage noted at last inspection.',
  },
  {
    id: 'p8',
    machineId: 'm3',
    partCode: 'IM-210',
    partName: 'Impeller',
    category: 'Rotating',
    serialNumber: 'IM210-1180',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Pump casing',
    fittedMonthsAgo: 12,
    expectedLifeMonths: 60,
  },

  // Conveyor Drive, Coal Handling
  {
    id: 'p9',
    machineId: 'm6',
    partCode: 'GB-450',
    partName: 'Gearbox Assembly',
    category: 'Power transmission',
    serialNumber: 'GB450-9021',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Drive unit',
    fittedMonthsAgo: 14,
    expectedLifeMonths: 14,
    notes: 'Replaced after overload failure.',
  },
  {
    id: 'p10',
    machineId: 'm6',
    partCode: 'CP-120',
    partName: 'Flexible Coupling',
    category: 'Power transmission',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Motor to gearbox',
    fittedMonthsAgo: 8,
    expectedLifeMonths: 36,
  },

  // Coal Yard Belt Conveyor, Coal Handling
  {
    id: 'p11',
    machineId: 'm53',
    partCode: 'IR-800',
    partName: 'Carrying Idler Roller',
    category: 'Rotating',
    quantity: 42,
    unit: 'pcs',
    positionOnMachine: 'Carry side, bays 1-8',
    fittedMonthsAgo: 20,
    expectedLifeMonths: 30,
  },
  {
    id: 'p12',
    machineId: 'm53',
    partCode: 'PL-140',
    partName: 'Drive Pulley Lagging',
    category: 'Wear parts',
    quantity: 1,
    unit: 'set',
    positionOnMachine: 'Head end drive pulley',
    fittedMonthsAgo: 22,
    expectedLifeMonths: 22,
  },
  {
    id: 'p13',
    machineId: 'm53',
    partCode: 'BS-090',
    partName: 'Belt Scraper Blade',
    category: 'Wear parts',
    quantity: 2,
    unit: 'pcs',
    positionOnMachine: 'Head end discharge',
    fittedMonthsAgo: 3,
    expectedLifeMonths: 6,
  },

  // Blast Furnace Blower
  {
    id: 'p14',
    machineId: 'm7',
    partCode: 'TB-300',
    partName: 'Thrust Bearing',
    category: 'Bearings',
    serialNumber: 'TB300-5560',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Blower shaft, drive side',
    fittedMonthsAgo: 16,
    expectedLifeMonths: 36,
  },
  {
    id: 'p15',
    machineId: 'm7',
    partCode: 'AF-410',
    partName: 'Inlet Air Filter',
    category: 'Consumable',
    quantity: 6,
    unit: 'pcs',
    positionOnMachine: 'Suction plenum',
    fittedMonthsAgo: 11,
    expectedLifeMonths: 12,
  },

  // Coke Pusher Machine
  {
    id: 'p16',
    machineId: 'm16',
    partCode: 'RM-770',
    partName: 'Pusher Ram Shoe',
    category: 'Wear parts',
    quantity: 2,
    unit: 'pcs',
    positionOnMachine: 'Ram head',
    fittedMonthsAgo: 9,
    expectedLifeMonths: 10,
  },
  {
    id: 'p17',
    machineId: 'm16',
    partCode: 'WH-220',
    partName: 'Travel Wheel',
    category: 'Rotating',
    quantity: 4,
    unit: 'pcs',
    positionOnMachine: 'Machine bogie',
    fittedMonthsAgo: 25,
    expectedLifeMonths: 48,
  },

  // Sinter Machine Drive, Sinter Plant 2
  {
    id: 'p18',
    machineId: 'm23',
    partCode: 'GB-980',
    partName: 'Grate Drive Gearbox',
    category: 'Power transmission',
    serialNumber: 'GB980-3312',
    quantity: 1,
    unit: 'pcs',
    positionOnMachine: 'Grate head shaft',
    fittedMonthsAgo: 28,
    expectedLifeMonths: 30,
  },
  {
    id: 'p19',
    machineId: 'm23',
    partCode: 'PT-060',
    partName: 'Pallet Car Wheel',
    category: 'Wear parts',
    quantity: 24,
    unit: 'pcs',
    positionOnMachine: 'Pallet cars 1-12',
    fittedMonthsAgo: 7,
    expectedLifeMonths: 18,
  },

  // Converter Tilting Drive, SMS3
  {
    id: 'p20',
    machineId: 'm27',
    partCode: 'TD-140',
    partName: 'Tilting Drive Pinion',
    category: 'Power transmission',
    serialNumber: 'TD140-6604',
    quantity: 2,
    unit: 'pcs',
    positionOnMachine: 'Trunnion ring drive',
    fittedMonthsAgo: 15,
    expectedLifeMonths: 42,
  },
  {
    id: 'p21',
    machineId: 'm27',
    partCode: 'BK-070',
    partName: 'Brake Lining Set',
    category: 'Wear parts',
    quantity: 1,
    unit: 'set',
    positionOnMachine: 'Tilt drive brake',
    fittedMonthsAgo: 13,
    expectedLifeMonths: 13,
  },

  // Slab Reheating Furnace, Plate Mill
  {
    id: 'p22',
    machineId: 'm64',
    partCode: 'BN-510',
    partName: 'Furnace Burner Nozzle',
    category: 'Combustion',
    quantity: 18,
    unit: 'pcs',
    positionOnMachine: 'Soak zone, both walls',
    fittedMonthsAgo: 21,
    expectedLifeMonths: 24,
  },
  {
    id: 'p23',
    machineId: 'm64',
    partCode: 'TC-330',
    partName: 'Zone Thermocouple',
    category: 'Instrumentation',
    quantity: 12,
    unit: 'pcs',
    positionOnMachine: 'Zones 1-6',
    fittedMonthsAgo: 6,
    expectedLifeMonths: 18,
  },

  // Wagon Tippler, Traffic
  {
    id: 'p24',
    machineId: 'm49',
    partCode: 'HC-260',
    partName: 'Clamping Hydraulic Cylinder',
    category: 'Hydraulics',
    serialNumber: 'HC260-8123',
    quantity: 4,
    unit: 'pcs',
    positionOnMachine: 'Wagon clamps',
    fittedMonthsAgo: 19,
    expectedLifeMonths: 36,
  },
  {
    id: 'p25',
    machineId: 'm49',
    partCode: 'RL-410',
    partName: 'Tippler Roller Assembly',
    category: 'Rotating',
    quantity: 8,
    unit: 'pcs',
    positionOnMachine: 'Cradle rollers',
    fittedMonthsAgo: 34,
    expectedLifeMonths: 30,
  },
];

function monthsAgo(months: number): string {
  const date = new Date();
  date.setMonth(date.getMonth() - months);
  return date.toISOString().slice(0, 10);
}

function buildPart(seed: PartSeed): MachinePart {
  const machine = mockMachines.find((candidate) => candidate.id === seed.machineId);
  const fittedDate = monthsAgo(seed.fittedMonthsAgo);

  return {
    id: seed.id,
    machineId: seed.machineId,
    machineName: machine?.name ?? 'Unknown machine',
    machineCode: machine?.code ?? '—',
    partCode: seed.partCode,
    partName: seed.partName,
    category: seed.category,
    serialNumber: seed.serialNumber,
    quantity: seed.quantity,
    unit: seed.unit,
    positionOnMachine: seed.positionOnMachine,
    fittedDate,
    expectedLifeMonths: seed.expectedLifeMonths,
    notes: seed.notes ?? '',
    isArchived: false,
    createdAt: new Date(fittedDate).toISOString(),
    updatedAt: new Date(fittedDate).toISOString(),
  };
}

export const mockParts: MachinePart[] = partSeeds.map(buildPart);

export const mockPartReplacements: PartReplacement[] = [
  {
    id: 'pr1',
    partId: 'p9',
    machineId: 'm6',
    replacedOn: monthsAgo(14),
    reason: 'Gearbox failure under sustained overload',
    previousSerialNumber: 'GB450-4417',
    newSerialNumber: 'GB450-9021',
    performedBy: 'u2',
    notes: 'Root cause traced to blocked chute loading the belt.',
  },
  {
    id: 'pr2',
    partId: 'p1',
    machineId: 'm1',
    replacedOn: monthsAgo(10),
    reason: 'Scheduled life expiry',
    previousSerialNumber: 'HF220-6650',
    newSerialNumber: 'HF220-8891',
    performedBy: 'u1',
  },
  {
    id: 'pr3',
    partId: 'p13',
    machineId: 'm53',
    replacedOn: monthsAgo(3),
    reason: 'Blade worn beyond adjustment range',
    performedBy: 'u2',
  },
];

/**
 * Preview-only image metadata. `url` points at a data URI placeholder rather than a
 * remote asset so the frontend phase never depends on Cloudinary or the network.
 */
const placeholderImageUrl =
  'data:image/svg+xml;utf8,' +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420">' +
      '<rect width="640" height="420" fill="#1e293b"/>' +
      '<text x="320" y="210" fill="#94a3b8" font-family="sans-serif" font-size="28" ' +
      'text-anchor="middle">Preview image</text></svg>',
  );

export const mockAttachments: Attachment[] = [
  {
    id: 'a1',
    entityId: 'm1',
    entityType: 'machine',
    fileName: 'hydraulic-press-front.svg',
    fileType: 'image/svg+xml',
    fileSize: 412_000,
    uploadedBy: 'u1',
    uploadedAt: '2023-09-10T09:15:00.000Z',
    url: placeholderImageUrl,
  },
  {
    id: 'a3',
    entityId: 'm2',
    entityType: 'machine',
    fileName: 'rolling-mill-motor.svg',
    fileType: 'image/svg+xml',
    fileSize: 350_100,
    uploadedBy: 'u1',
    uploadedAt: '2023-10-01T11:05:00.000Z',
    url: placeholderImageUrl,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'al1',
    entityId: 'm1',
    entityType: 'machine',
    action: 'created',
    performedBy: 'u1',
    performedAt: '2019-03-15T06:30:00.000Z',
    changes: 'Machine HP-04 registered in the machine register.',
  },
  {
    id: 'al2',
    entityId: 'm1',
    entityType: 'machine',
    action: 'updated',
    performedBy: 'u1',
    performedAt: '2023-09-10T09:10:00.000Z',
    changes: 'Last maintenance date updated after preventive service.',
  },
  {
    id: 'al3',
    entityId: 'm1',
    entityType: 'machine',
    action: 'image_set',
    performedBy: 'u2',
    performedAt: '2023-09-10T09:22:00.000Z',
    changes: 'Set machine image hydraulic-press-front.svg.',
  },
  {
    id: 'al4',
    entityId: 'm2',
    entityType: 'machine',
    action: 'created',
    performedBy: 'u1',
    performedAt: '2017-08-20T05:45:00.000Z',
    changes: 'Machine RM-12 registered in the machine register.',
  },
  {
    id: 'al5',
    entityId: 'm2',
    entityType: 'machine',
    action: 'status_changed',
    performedBy: 'u2',
    performedAt: '2023-10-01T08:00:00.000Z',
    changes: 'Status changed from Active to Under Maintenance.',
  },
  {
    id: 'al6',
    entityId: 'm15',
    entityType: 'machine',
    action: 'archived',
    performedBy: 'u1',
    performedAt: '2023-01-01T10:00:00.000Z',
    changes: 'Machine CB-05 archived after decommissioning.',
  },
];

export const getDashboardSummary = (): DashboardSummary => {
  return {
    totalMachines: mockMachines.length,
    active: mockMachines.filter((m) => m.status === 'active').length,
    inactive: mockMachines.filter((m) => m.status === 'inactive').length,
    underMaintenance: mockMachines.filter((m) => m.status === 'under_maintenance').length,
    underRepair: mockMachines.filter((m) => m.status === 'under_repair').length,
    dueSoon: mockMachines.filter((m) => m.status === 'active' && isDueSoon(m.nextMaintenanceDate))
      .length,
    overdue: mockMachines.filter(
      (m) =>
        isOverdue(m.nextMaintenanceDate) &&
        m.status !== 'retired' &&
        m.status !== 'under_maintenance' &&
        m.status !== 'under_repair',
    ).length,
    retired: mockMachines.filter((m) => m.status === 'retired').length,
    recentlyAdded: [...mockMachines]
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 4),
    needsAttention: mockMachines
      .filter(
        (m) =>
          m.status === 'under_repair' ||
          m.status === 'under_maintenance' ||
          (isOverdue(m.nextMaintenanceDate) && m.status === 'active'),
      )
      .slice(0, 5),
    upcomingMaintenance: mockMaintenanceRecords
      .filter((m) => m.status === 'scheduled')
      .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime())
      .slice(0, 7),
    recentRepairs: [...mockRepairRecords]
      .sort((a, b) => new Date(b.reportedDate).getTime() - new Date(a.reportedDate).getTime())
      .slice(0, 5),
  };
};
